### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by asdasd45asda** [AdvDebug/AntiCrack-DotNet#2]
del

**Comment by AdvDebug** [comment]
it's not a winform project, my project is a console project. also i can't help you without any additional information

**Comment by asdasd45asda** [comment]
I think the problem is here Always perceives it as bad

   if (Result == "[Bad]" || Result == "Failed")
            {

**Comment by AdvDebug** [comment]
where's the rest of the code? anyway, you can always modify the functions inside the classes to return true/false and you don't need to depend on "strings" i putted cause i just did that to make it easier to show results in the console.

**Comment by AdvDebug** [comment]
No Response

**Comment by asdasd45asda** [comment]
public static void DisplayCheckResult(string Text, bool Result)
        {
            if (Result == true)
            {
                Console.Write(Text);
                Console.ForegroundColor = ConsoleColor.DarkRed;
                Console.Write("[Bad]" + "\n\n");
                Console.ForegroundColor = ConsoleColor.White;
            }
            else
            {
                Console.Write(Text);
                Console.ForegroundColor = ConsoleColor.DarkGreen;
                Console.Write("[Good]" + "\n\n");
                Console.ForegroundColor = ConsoleColor.White;
            }
        }

        public static void DisplayCheckResult(string Text, string Result)
        {
            if (Result == "[Bad]" || Result == "Failed")
            {
                Console.Write(Text);
                Console.ForegroundColor = ConsoleColor.DarkRed;
                Console.Write(Result + "\n\n");
                Console.ForegroundColor = ConsoleColor.White;
            }
            else if (Result == "Skipped")
            {
                Console.Write(Text);
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                Console.Write($"[{Result}]" + "\n\n");
                Console.ForegroundColor = ConsoleColor.White;
            }
            else
            {
                Console.Write(Text);
                Console.ForegroundColor = ConsoleColor.DarkGreen;
                Console.Write(Result + "\n\n");
                Console.ForegroundColor = ConsoleColor.White;
            }
        }


continually perceives it as bad
