### ISSUE TITLE
Access Violation during AntiDllInjection

### ISSUE THREAD

**Issue by emanueleriboldi** [AdvDebug/AntiCrack-DotNet#3]
All things go fine until here:

`Application.Run(new Form1());`

after that, the software throws an "Access Violation".
I did some debug and the problem is caused by ExecuteAntiDllInjectionTricks().
Any clues?

**Comment by AdvDebug** [comment]
just stop using the LoadLibraryA and LoadLibraryW patching and it should work

**Comment by emanueleriboldi** [comment]
> just stop using the LoadLibraryA and LoadLibraryW patching and it should work

I will test today and let you know

**Comment by emanueleriboldi** [comment]
> just stop using the LoadLibraryA and LoadLibraryW patching and it should work

Hello, I've tested it and after this change, the sofware starts to give strange errors, like something about Bonjour DLL, then it opens random blank Forms... I don't know what is happening. I suggest to check, but I've disabled AntiDllInjection.

**Comment by AdvDebug** [comment]
i suggest you to enable it after everything have loaded because it really depends on when you apply the protection (especially in .NET or other languages that manages itself)

**Comment by emanueleriboldi** [comment]
> i suggest you to enable it after everything have loaded because it really depends on when you apply the protection (especially in .NET or other languages that manages itself)

You mean after all protections are loaded or at the end of the software?

**Comment by AdvDebug** [comment]
no i meant after all dlls of .NET are loaded or after the form appears for example

**Comment by emanueleriboldi** [comment]
> no i meant after all dlls of .NET are loaded or after the form appears for example

Well the problem is that this is a winform project, it has many forms that opens, so I don't know where I can put this line.

**Comment by AdvDebug** [comment]
closed because this is not related to the project
